In [25]:
import numpy as np

In [26]:
lista=[1,2,3]

In [27]:
np.array(lista)

array([1, 2, 3])

In [28]:
print(np.array(lista))
# Tiene forma de vector

[1 2 3]


In [29]:
arreglo=np.array(lista)

In [30]:
arreglo.dtype

dtype('int32')

In [31]:
arreglo[0]

1

#### Ejercicio: sumar 2 listas

In [32]:
[1,2,3]+[4,5,6]

[1, 2, 3, 4, 5, 6]

In [33]:
arreglo

array([1, 2, 3])

In [34]:
arreglo + arreglo
#Se suma el primero de un arreglo con el primero de otro arreglo

array([2, 4, 6])

In [35]:
arreglo2=[10,20,30, 40]

In [36]:
#arreglo+arreglo2

##### Ejercicio: Obtener una lista que contenga los números al cuadrado del 1 al 10

In [37]:
Li=[]
for i in range(1,11):
    Li.append(i**2)
Li

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [38]:
[x**2 for x in range(1,11)]
#List comprehension

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [39]:
np.arange(1,11)**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [40]:
np.array(arreglo2)+150

array([160, 170, 180, 190])

#### Calcular el IMC

In [41]:
peso=[80.4,74.5,99.5,75.9,105.5]

In [42]:
estatura=[1.80,1.65,1.72,1.63,1.80]

In [43]:
imc=[]
for i in range(len(peso)):
    imc.append(peso[i]/estatura[i]**2)
imc

[24.814814814814817,
 27.364554637281913,
 33.63304488912926,
 28.567127103014794,
 32.56172839506173]

In [44]:
imc_1=np.array(peso)/np.array(estatura)**2
imc_1

array([24.81481481, 27.36455464, 33.63304489, 28.5671271 , 32.5617284 ])

$$ imc=\frac{peso}{estatura^2} $$

In [45]:
ejemplo=np.array([1,2,3,"5"])
ejemplo

array(['1', '2', '3', '5'], dtype='<U11')

Condicionales

In [46]:
15<20

True

In [47]:
imc_1>30

array([False, False,  True, False,  True])

Filtro

In [48]:
imc_1[imc_1>30]

array([33.63304489, 32.5617284 ])

In [49]:
list(imc_1[imc_1>30])

[33.63304488912926, 32.56172839506173]

## Crear arrays

In [50]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [51]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [52]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [53]:
np.arange(15,31)

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [54]:
np.arange(10,31,5)

array([10, 15, 20, 25, 30])

Linspace

In [55]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [56]:
np.linspace(0,100,4)

array([  0.        ,  33.33333333,  66.66666667, 100.        ])

In [57]:
np.linspace(-5,5,10)

array([-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
        0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ])

In [58]:
np.random.randint(10)

2

In [59]:
np.random.randint(50,100)

79

In [60]:
np.random.randint(50,100,10)

array([85, 92, 83, 64, 68, 97, 81, 69, 77, 52])

In [61]:
numers_aleatorios=np.random.randint(10,20,10)
numers_aleatorios.sort()
numers_aleatorios

array([10, 10, 10, 12, 14, 15, 16, 16, 16, 16])

# Matrices

In [62]:
sublista=[ [1.80,83.4],[1.76,80.5],[1.78,82.5]]

In [63]:
matriz=np.array(sublista)
matriz

array([[ 1.8 , 83.4 ],
       [ 1.76, 80.5 ],
       [ 1.78, 82.5 ]])

In [64]:
matriz[:,0]

array([1.8 , 1.76, 1.78])

In [65]:
matriz.shape

(3, 2)

matriz([0,0])

In [66]:
matriz[0,:]

array([ 1.8, 83.4])

In [67]:
matriz[1:,:]

array([[ 1.76, 80.5 ],
       [ 1.78, 82.5 ]])

In [68]:
matriz[[0,2],:]

array([[ 1.8 , 83.4 ],
       [ 1.78, 82.5 ]])

In [69]:
np.where(matriz>1.79)

(array([0, 0, 1, 2], dtype=int64), array([0, 1, 1, 1], dtype=int64))

In [70]:
filas, columnas=np.where(matriz>1.79)
filas

array([0, 0, 1, 2], dtype=int64)

In [71]:
columnas

array([0, 1, 1, 1], dtype=int64)

In [72]:
for fila,columna in zip(filas,columnas):
    print(f"{fila} {columna} {matriz[fila][columna]}")

0 0 1.8
0 1 83.4
1 1 80.5
2 1 82.5


In [73]:
import pandas as pd

In [74]:
data= pd.read_csv("https://assets.datacamp.com/production/repositories/288/datasets/026a5211b906ac118a09b1a0dbf7df48faafb379/fifa.csv")

In [75]:
data

id                     name   rating  position   height    foot  \
0       1001             Gábor Király       69        GK      191   Right   
1     100143             Frederik Boi       65         M      184   Right   
2     100264          Tomasz Szewczuk       57         A      185   Right   
3     100325   Steeve Joseph-Reinette       63         D      180    Left   
4     100326             Kamel Chafni       72         M      181   Right   
...      ...                      ...      ...       ...      ...     ...   
8842    9801          Danijel Ljuboja       73         A      189    Left   
8843    9805            Craig Bellamy       79         A      175   Right   
8844    9807            Michel Breuer       68         D      183   Right   
8845    9815              Gill Swerts       65         D      179   Right   
8846    9913              Mehdi Nafti       69         M      179   Right   

       rare  pace  shooting  passing  dribbling  defending  heading  diving  \
0         0                                                              70   
1         0    61        65       63         59         62       62           
2         0    65        54       43         53         55       74           
3         0    68        38       51         46         64       71           
4         0    75        64       67         72         57       66           
...     ...   ...       ...      ...        ...        ...      ...     ...   
8842      1    62        73       64         74         56       68           
8843      0    80        78       67         81         62       71           
8844      0    61        40       56         51         70       74           
8845      0    65        48       63         65         67       69           
8846      0    55        56       64         65         69       60           

      handling  kicking  reflexes  speed   positioning  
0           66       63        74     35          66.0  
1                                                  NaN  
2                                                  NaN  
3                                                  NaN  
4                                                  NaN  
...        ...      ...       ...    ...           ...  
8842                                               NaN  
8843                                               NaN  
8844                                               NaN  
8845                                               NaN  
8846                                               NaN  

[8847 rows x 19 columns]

In [76]:
data.columns

Index(['id', ' name', ' rating', ' position', ' height', ' foot', ' rare',
       ' pace', ' shooting', ' passing', ' dribbling', ' defending',
       ' heading', ' diving', ' handling', ' kicking', ' reflexes', ' speed',
       ' positioning'],
      dtype='object')

In [77]:
data[" name"]

0                  Gábor Király
1                  Frederik Boi
2               Tomasz Szewczuk
3        Steeve Joseph-Reinette
4                  Kamel Chafni
                 ...           
8842            Danijel Ljuboja
8843              Craig Bellamy
8844              Michel Breuer
8845                Gill Swerts
8846                Mehdi Nafti
Name:  name, Length: 8847, dtype: object

In [78]:
data[" name"].values

array([' Gábor Király', ' Frederik Boi', ' Tomasz Szewczuk', ...,
       ' Michel Breuer', ' Gill Swerts', ' Mehdi Nafti'], dtype=object)

In [79]:
positions= data[" position"].values

In [80]:
heights=data[" height"].values
heights

array([191, 184, 185, ..., 183, 179, 179], dtype=int64)

In [81]:
positions==" GK"

array([ True, False, False, ..., False, False, False])

In [82]:
hgk=heights[positions==" GK"]

In [83]:
hgk.mean()

188.23333333333332

In [84]:
hgk1=heights[~(positions==" GK")]

In [85]:
hgk1

array([184, 185, 180, ..., 183, 179, 179], dtype=int64)